name: Deploy PHP App

on:
  push:
    branches:
      - master
    workflow_distpach: #permite ejecutar manualmente desde githubs actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Verificar Variables de entorno
        run: |
		      echo "IP del Servidor : ${{ secrets.SERVER_IP }}"
		      echo "Usuario : ${{ secrets.SERVER_USER }}"
		      echo "Puerto SSH : ${{ secrets.SERVER_PORT }}"

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "."
          target: "/var/www/php-docker-ci-cd"

      - name: Construir y desplegar con Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/php-docker-ci-cd
            docker-compose down
            docker-compose up -d --build


